- name: My HomeLab Playbook
  hosts: raspberryPi
  become: true
  become_user: root

  roles:
  #- { role: common, tags: ['common'] }
  #- { role: docker, tags: ['docker'] }
  #- { role: jellyfin, tags: ['jellyfin'] }
  #- { role: samba, tags: ['samba'] }
  - { role: vault, tags: ['vault'] }
  - { role: reverse-proxy, tags: ['reverse-proxy'] }
